### PR TITLE
Removed "final" on StyledLabel

### PR DESCRIPTION
**Pull request by mjrehder**
I am creating a new component, which depends on this control and I would like to use the same styling elements in order to have matching styles. The new component needs to derive from the StyledLabel (extension is not adequate), so it would be nice if the "final" declaration is removed from StyledLabel.

### CODE REVIEW

**Comment by yannickl** [comment]
Ok, this is a good use case. Usually I make all my classes final by default, I remove the keyword only when a use case seems relevant like here. :)

**Comment by mjrehder** [comment]
Nothing against the final by default, it is a good principle. I need a couple of days for the first iteration of my new styled components. Maybe it will make sense at some point in time to refactor the StyledLabel out into its own repo.

**Comment by mjrehder** [comment]
I have created a new pod with the mentioned project: https://github.com/mjrehder/MJRFlexStyleComponents
However, it seems that I cannot depend on the master branch of SnappingStepper when publishing to cocoapods. Version 2.3.0 still has the "final" class for StyledLabel.
Any chance of making a new version? Please :-)

**Comment by yannickl** [comment]
Sorry, I was waiting for any new feature or other, but nothing has changed.

I just published a new version (2.3.1) with the last changes.

Best

**Comment by mjrehder** [comment]
Ok, thanks. Just released MJRFlexStyleComponents to cocoapods sucessfully.

**Pull request merged**
