### PR TITLE
Xcode10 and Swift 4.2

### PR DESCRIPTION
**Pull request by ergunkocak**

### CODE REVIEW

**Comment by ergunkocak** [comment]
CocoaPods could not find compatible versions for pod "DynamicColor" ???
xcode 7.3 ???
What is going on :D

**Comment by yannickl** [comment]
Thank you for your help! I'll update the travis file and the cocoapods dependency versions.

**Comment by ergunkocak** [comment]
Hi,
New version is not displayed in Releases : https://github.com/yannickl/SnappingStepper/releases
Also home readme may need an update about the version

**Comment by yannickl** [comment]
@ergunkocak I just pushed a new version. ;)

**Pull request merged**
